### PR TITLE
fix broken xref

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by paigehargrave** [comment]
Hi @mojavelinux - Link on https://docs.mulesoft.com/private-cloud/2.0/upgrade is working.  Is your mulesoft:v2.0 branch current?

**Comment by mojavelinux** [comment]
This is a new restriction when using Antora 2.3. The xref was always wrong, but Antora < 2.3 was letting it slide. That's no longer the case. So we need this fix in order to complete the upgrade to Antora 2.3.

**Comment by mojavelinux** [comment]
FYI, starting in Antora 3, the .adoc file extension will always be required on the page ID. See https://docs.antora.org/antora/2.3/whats-new/#fix-regression-when-resolving-page-id-with-version-and-no-file-extension for what is currently permitted and what is not.

**Comment by paigehargrave** [comment]
Ah - ok - thank you for the information! I'll go ahead and approve this - please merge when needed.

**Review by paigehargrave — APPROVED** [review]

**Comment by mojavelinux** [comment]
Thanks!

**Pull request merged**
